### PR TITLE
Removed code backward compatible with node < v0.12

### LINKED ISSUE #42: Binding: Remove backwards compatible #ifdef code
For the assigned node >= 0.12.x milestone, the #ifdef code is not necessary anymore.

### PR DESCRIPTION
**Pull request by thmiceli**
Closes #42

### CODE REVIEW

**Comment by ericvw** [comment]
@thmiceli, can you rebase?  I force pushed `node-v0.12` to update the `.travis.yml` file.

**Comment by ericvw** [comment]
I promise I won't rewrite history again on this branch :)

**Comment by thmiceli** [comment]
Rebased.

**Comment by ericvw** [comment]
lgtm and TravisCI appears happy.

**Pull request merged**
