### PR TITLE
Update Linux/Windows BLPAPI to v3.8.8.1.

### LINKED ISSUE #56: Dep: Bump blpapi C++ SDK dependency
The latest [BLPAPI libraries](http://www.bloomberglabs.com/api/libraries/) are at the following versions that should be upgraded to:
* Windows: 3.8.8.1
* Linux: 3.8.8.1
* OSX: 3.8.1.1 (experimental)

### PR DESCRIPTION
**Pull request by apaprocki**
Fixes #56.

### CODE REVIEW

**Comment by apaprocki** [comment]
#32 should also be re-tested once the new stable version lands.

**Comment by apaprocki** [comment]
@ericvw Didn't realize this one was still outstanding.. any issues on your end?

**Comment by ericvw** [comment]
I believe the DLL is needed for Windows.  I'll verify and provide an update.

**Comment by ericvw** [comment]
@apaprocki, please rebase your changes against the latest `master`.  We dropped support for node < `0.11.0`, which is why we are getting the build failures.  I'll test these changes on Windows tomorrow.

**Comment by apaprocki** [comment]
@ericvw rebased, Travis building it now...

**Comment by ericvw** [comment]
I tested this PR on my Windows VM and it all checks out.

**Pull request merged**
